version: '3'
services:
  spring:
    build: .
    image: dannyelcf/tdd-lab-spring
    working_dir: /tdd-lab/spring
    volumes:
       - ${PWD}:/tdd-lab/spring
       - ${HOME}/.m2:/root/.m2
    ports:
       - '8080:8080'

