language: java

service: docker

before_install:
  - docker build -t dannyelcf/tdd-lab-javaee6 javaee6/.docker
  - docker build -t dannyelcf/tdd-lab-spring spring/.docker

install: true

script:
  - javaee6/reservation/./mvnw clean test -B 
  - spring/reservation/./mvnw clean test -B

cache:
  directories:
  - $HOME/.m2/repository